### ISSUE TITLE
About the difference between two similar projects.

### ISSUE THREAD

**Issue by hongyi-zhao** [emacs-openai/codegpt#7]
What's the difference between the following two projects?

https://github.com/emacs-openai/codegpt
https://github.com/joshcho/ChatGPT.el

Regards,
Zhao

**Comment by jcs090218** [comment]
A few differences,

- `codegpt` only uses official API, `ChatGPT.el` uses python wrapper from a third party library [chatgpt-wrapper](https://github.com/mmabrouk/chatgpt-wrapper).
- `codegpt` cannot make continuous request like `ChatGPT.el` because there is no official API for ChatGPT at the moment.

The rest are pretty much the same. As of now, `ChatGPT.el` can do more than `codegpt` due to their hacky method. Once OpenAI has officially established ChatGPT's API in the future, then I will integrate those to https://github.com/emacs-openai/openai.

*(Side note, I don't prefer third-party library and Python is particularly bad on Windows.)*

**Comment by hongyi-zhao** [comment]
- As commented [here](https://medium.com/geekculture/using-chatgpt-in-python-eeaed9847e72), [chatgpt-wrapper](https://github.com/mmabrouk/chatgpt-wrapper) is slow:

![image](https://user-images.githubusercontent.com/11155854/221465482-156ec7f3-989f-4711-96d1-bf310e69cf30.png)

Does this mean that `codegpt` is faster than `ChatGPT.el`?

-  Does `codegpt` use [`openai`](https://github.com/emacs-openai/openai) under the hood?

**Comment by jcs090218** [comment]
> Does this mean that codegpt is faster than ChatGPT.el?

I assumed. I've seen their source code, it will extract data from HTML page, so yes, it should be slower than regular REST API. 

> * Does codegpt use [openai](https://github.com/emacs-openai/openai) under the hood?

Yes, https://github.com/emacs-openai/codegpt/blob/master/codegpt.el#L9.

**Comment by hongyi-zhao** [comment]
> * `codegpt` cannot make continuous request like `ChatGPT.el` because there is no official API for ChatGPT at the moment.

What do you mean by saying `continuous request`, and if there were a remedial measure to make up for?

**Comment by jcs090218** [comment]
> What do you mean by saying continuous request, and if there were a remedial measure to make up for?

I mean "making conversation". Sorry for the confusion! 😅

**Comment by hongyi-zhao** [comment]
If this is the case, it means that, with your method, the `ChatGPT`'s context associative capabilities will not be fully utilized to solve complex problems. On the other hand, it also adds to the user's skill in asking questions and the amount of work required to enter information. Am I right?

**Comment by jcs090218** [comment]
Since `codegpt` doesn't use ChatGPT, so yes.
